Dev/bigdatastoragehandler
IoTKETI/citydatahub_data_core_module pull request #54
Opened 2023-05-03 11:58 UTC by dhkdlwpdl

- Docker 테스트 환경 수정
  - hbase 도커 환경 추가
  - postgres locale 설정 추가
- Hbase 관련 설치 가이드 수정
  - 수동 설치 방법 간소화

2023-05-04 01:56 UTC, vanilet commented on bigdatastorage/docker/postgis/Dockerfile
> +RUN apt-get update && apt-get install -y locales && \
12번 라인과 통합해주시길 바랍니다.

2023-05-05 05:43 UTC, vanilet requested changes
hbase 컨테이너가 실행되지 않습니다. 아래 컨테이너 로그를 참고해주세요.

exec /entrypoint.sh: no such file or directory

2023-05-08 01:47 UTC, dhkdlwpdl commented
> hbase 컨테이너가 실행되지 않습니다. 아래 컨테이너 로그를 참고해주세요.
> 
> exec /entrypoint.sh: no such file or directory

윈도우, 리눅스 간의 개행문자 이슈로 파악됩니다. 
hbase Dockerfile에 entrypoint.sh 파일의 개행문자를 crlf -> lf 로 변경해주는 내용을 추가했습니다.

2023-05-08 01:51 UTC, dhkdlwpdl commented
> hbase 컨테이너가 실행되지 않습니다. 아래 컨테이너 로그를 참고해주세요.
> 
> exec /entrypoint.sh: no such file or directory

윈도우 <-> 리눅스 간의 개행문자 이슈로 파악됩니다.
HBase Dockerfile에 entrypoint.sh 파일의 개행문자를 crlf -> lf 로 변경해주는 내용을 추가했습니다.

2023-05-09 05:52 UTC, merged